name: Report a bug
description: Let us know if something’s not working as expected
labels:
  - bug
  - awaiting triage
body:
  - type: markdown
    attributes:
      value: |
        You’re reporting a bug in MOD.UK Frontend. All questions are optional – fill in as much of the form as you’re able to.
        
        All issues created in this repository are public. Do not include any sensitive information.
  - type: textarea
    id: repro-steps
    attributes:
      label: What steps will reproduce the bug?
      description: Include a code snippet or public link if relevant
  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
  - type: textarea
    id: actual
    attributes:
      label: What happened instead?
      description: Attach a screenshot or screen recording if relevant
  - type: input
    id: version
    attributes:
      label: What version of MOD.UK Frontend were you using?
      description: The version of the @moduk/frontend package the problem was seen in
  - type: input
    id: browser
    attributes:
      label: What web browsers have you seen this in?
      description: For example, Firefox 108 or Chrome 105
  - type: input
    id: operating-system
    attributes:
      label: What operating system were you using?
      description: For example, Windows 10 or Android 13
  - type: textarea
    id: additional-info
    attributes:
      label: Context and anything else
      description: What are you trying to accomplish? How has this issue affected you? Do you have a suggested fix?
