name: Release

concurrency:
  group: ${{ github.workflow }}

on:
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    steps:
      - name: Git clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: npm install
        run: npm install

      - name: Configure Git user
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git config push.autoSetupRemote true

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run release
