name: Release

on:
  workflow_dispatch:

jobs:
  branch:
    name: Branch
    runs-on: ubuntu-latest
    steps:
      - name: Git clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_TOKEN }}

      - name: Configure Git user
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

      - name: Create branch
        run: git switch -c release/test

      - name: Commit
        run: git commit --allow-empty -m "Empty commit"

      - name: Push
        run: git push origin release/test

      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.2.0
        with:
          ref: release/test
          check-name: 'Test'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - name: Merge
        run: |
          git switch main
          git merge release/test
          git push origin main
