name: Release

on:
  workflow_dispatch:

jobs:
  branch:
    name: Branch
    runs-on: ubuntu-latest
    steps:
      - name: Git clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git user
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

      - name: Create branch
        run: git switch -c release/test

      - name: Commit
        run: git commit --allow-empty -m "Empty commit"

      - name: Push
        run: git push origin release/test

  test:
    name: Test
    needs:
      - branch
    uses: ./.github/workflows/test.yml
    with:
      git-ref: release/test

  merge:
    name: Merge
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Git clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git user
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

      - name: Merge
        run: |
          git merge origin/release/test
          git push -u
