name: Test

on:
  pull_request:
  push:
    branches:
      - main
      - release/**
  workflow_call:
    inputs:
      git-ref:
        description: 'Git ref'
        required: true
        default: ''
        type: string
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Git clone repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.git-ref }}

      - name: Test
        run: exit
