name: Lint and test

on:
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    name: Lint and test
    runs-on: ubuntu-latest
    steps:
      - name: Git clone repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.git-ref }}

      - name: Test
        run: exit
